version: 1.0.{build}

environment:
  matrix:

  - job_name: Windows 32
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: Windows 64
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: Ubuntu
    appveyor_build_worker_image: Ubuntu2004
    #appveyor_build_worker_image: Ubuntu1804

  - job_name: MacOS
    appveyor_build_worker_image: macOS

for:

  -
    matrix:
      only:
        - job_name: Windows 32

    build_script:
    - cmd: pipelines/win32_build.bat

  -
    matrix:
      only:
        - job_name: Windows 64

    build_script:
    - cmd: pipelines/win64_build.bat

  -
    matrix:
      only:
        - job_name: Ubuntu

    build_script:
    - sh: ./pipelines/linux_build.sh

  -
    matrix:
      only:
        - job_name: MacOS

    build_script:
    - sh: ./pipelines/macOS_build.sh

